#######################################################################
all: broadcast.o

#######################################################################

broadcast.o : broadcast.cpp
	mpicxx -O3 broadcast.cpp -o broadcast.exec



